name: Build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.20.5]
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credential: false

      - name: Create NPMRC ðŸ”§
        run: |
          cat npmrc.txt >> .npmrc

      - name: Install Dependences
        run: |
          npm install
      - name: Run Unit Tests ðŸ§ª
        run: |
          npm run test
        continue-on-error: false
      - name: Build App ðŸ”§
        run: |
          npm run generate
      - name: Sync files ðŸ“‚ Server hostinger.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_NAME }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          log-level: verbose
          protocol: ftps
          timeout: 120001
          local-dir: ./.output/public/
