name: Build
on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2
        with:
          persist-credential: false

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Create NPMRC ðŸ”§
        run: |
          cat npmrc.txt >> .npmrc

      - name: Install Dependences
        run: |
          npm install

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Run Unit Tests ðŸ§ª
        run: |
          npm run test
        continue-on-error: false

  build-app:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Build App ðŸ”§
        run: |
          npm run generate

  deploy:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Sync files ðŸ“‚ Server hostinger.com
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER_NAME }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true
          log-level: verbose
          protocol: ftps
          timeout: 120001
          local-dir: ./.output/public/
